### ISSUE TITLE
资源管理器dock无法关闭，菜单设置有重复设置项

### ISSUE THREAD

**Issue by TinkMingKing** [Zuoqiu-Yingyi/siyuan-plugin-monaco-editor#13]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/assets/32903588/43697ffe-6456-4bf7-a55f-6052a62319ac)
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/assets/32903588/6c16439d-e171-46ba-8a83-6087eb3b1372)

**Comment by Zuoqiu-Yingyi** [comment]
> ![image](https://user-images.githubusercontent.com/32903588/273369345-6c16439d-e171-46ba-8a83-6087eb3b1372.png)

- 文件历史是使用快捷键 <kbd>Alt + H</kbd> 打开的面板
- 文档历史是右键单击文档树 > 文件历史菜单项 打开的面板

**Comment by TinkMingKing** [comment]
看走眼了
