### ISSUE TITLE
显示的文本内容又不能自动换行了，已经开启代码换行模式

### ISSUE THREAD

**Issue by mozhux** [Zuoqiu-Yingyi/siyuan-plugin-monaco-editor#21]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/assets/46953371/cd16bcee-e1b3-4ddd-840f-ac22aa33ea7a)

**Comment by Zuoqiu-Yingyi** [comment]
是最新版本 `v0.2.2` 吗, 我这里可以正常换行

**Comment by mozhux** [comment]
> 是最新版本 `v0.2.2` 吗, 我这里可以正常换行

是的，思源是2.11.1 插件是0.2.2 然后不是指的代码，是指的右侧显示时正常文本的宽度自动换行，我记得之前是支持的？

**Comment by Zuoqiu-Yingyi** [comment]
自动换行需要使用快捷键 <kbd>Alt + Z</kbd> 或者右键菜单手动开启

**Comment by mozhux** [comment]
收到，我的问题

**Comment by Achuan-2** [comment]
希望能记忆自动换行

**Comment by Zuoqiu-Yingyi** [comment]
> 希望能记忆自动换行

在设置面板添加了一个下拉选项框, 用于设置默认折行方案
在编辑器中使用快捷键则是临时切换折行方案
