### ISSUE TITLE
在2.12.4版本中，有出现图标变大的问题

### ISSUE THREAD

**Issue by edward-kyle** [Zuoqiu-Yingyi/siyuan-plugin-monaco-editor#24]
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/assets/78415230/89da4432-dbbd-478f-bbeb-b5299d1b0364)

虽然不影响使用，但是太不美观了

**Comment by TCOTC** [comment]
我在默认主题下会出现这样的情况，使用写味主题就不会
