### ISSUE TITLE
每次打开思源笔记时，会移动到下侧右方Dock栏，并打开

### ISSUE THREAD

**Issue by TCOTC** [Zuoqiu-Yingyi/siyuan-plugin-monaco-editor#25]
无论关闭思源笔记时移动到哪里，再次打开思源笔记时就如图：

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/assets/78434827/d9e6baaf-2244-476a-a8d5-2c45d3062a45)

**Comment by TCOTC** [comment]
v2.12.4

**Comment by Zuoqiu-Yingyi** [comment]
这个是思源的 bug, 所有插件的自定义侧边面板都不能保存布局, 建议在 [New Issue · siyuan-note/siyuan](https://github.com/siyuan-note/siyuan/issues/new/choose) 中反馈

**Comment by TCOTC** [comment]
在Dock栏的位置确实是不能保存。不过插件是否不应该默认打开？

**Comment by Zuoqiu-Yingyi** [comment]
> 在Dock栏的位置确实是不能保存。不过插件是否不应该默认打开？

侧边栏 位置 & 是否打开 & 打开后的宽度 都是思源布局的一部分, 是统一保存的

**Comment by QMike0** [comment]
+1，这个是最近才出现的问题
另外，由于我将这个插件的「文件资源管理器」icon放在思源dock栏左上方，即使我默认打开的是文档树，每次打开思源/切换主题的时候，都会默认开启「文件资源管理器」+右下角的「代码编辑」，需要手动调回去...
给一种感觉就是每次只要刷新思源界面，这个插件就会自己“火力全开”
![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/assets/43239563/12bb3cbc-2b66-4660-b022-546485070f79)

**Comment by TCOTC** [comment]
V 姐说是插件的问题：https://github.com/siyuan-note/siyuan/issues/10237#issuecomment-1907393941

**Comment by TCOTC** [comment]
> 每次只要刷新思源界面，这个插件就会自己“火力全开”

@QMike0 这个说法挺有趣的。因为我不频繁使用插件，所以我现在暂时关闭了侧边面板（在插件设置中）：

![image](https://github.com/Zuoqiu-Yingyi/siyuan-plugin-monaco-editor/assets/78434827/e671f66d-b3f5-46fb-8dc4-e110053cf587)

**Comment by Zuoqiu-Yingyi** [comment]
已于思源 `v2.12.5` 修复

**Comment by winter60** [comment]
[v2.12.6 退出应用后又会重置布局 - 链滴](https://ld246.com/article/1706636185893)  似乎新版仍然会关闭已经打开的文档，会打开dock栏 @Zuoqiu-Yingyi

**Comment by Zuoqiu-Yingyi** [comment]
> 新版仍然会关闭已经打开的文档

能具体描述一下操作步骤吗

**Comment by winter60** [comment]
> 能具体描述一下操作步骤吗

就像链滴中的视频一样，打开一文档，退出应用，启动应用，之前的文档被关掉，两个插件的dock栏也都展开了。

**Comment by Achuan-2** [comment]
能否关闭dock栏，但是块右键菜单依然能用集成编辑环境呢
